merged git with wdf code

diff --git a/SAPHana/SAPHana b/SAPHana/SAPHana
--- a/SAPHana/SAPHana
+++ b/SAPHana/SAPHana
@@ -2,7 +2,7 @@
 #
 # SAPHana
 #
-# Description:	Manages two single SAP HANA Instance in System Replication 
+# Description:  Manages two single SAP HANA Instance in System Replication 
 #               Planned: do also manage scale-up scenarios
 #               currently the SAPHana is dependent of the analysis of 
 #               SAPHanaTopology
@@ -21,11 +21,11 @@
 #      See usage() function below for more details...
 #
 # OCF instance parameters:
-#	OCF_RESKEY_SID
-#	OCF_RESKEY_InstanceNumber       
-#	OCF_RESKEY_DIR_EXECUTABLE   (optional, well known directories will be searched by default)
-#	OCF_RESKEY_DIR_PROFILE      (optional, well known directories will be searched by default)
-#	OCF_RESKEY_INSTANCE_PROFILE (optional, well known directories will be searched by default)
+#   OCF_RESKEY_SID
+#   OCF_RESKEY_InstanceNumber       
+#   OCF_RESKEY_DIR_EXECUTABLE   (optional, well known directories will be searched by default)
+#   OCF_RESKEY_DIR_PROFILE      (optional, well known directories will be searched by default)
+#   OCF_RESKEY_INSTANCE_PROFILE (optional, well known directories will be searched by default)
 #   OCF_RESKEY_PREFER_SITE_TAKEOVER (optional, default is no)
 #   OCF_RESKEY_DUPLICATE_PRIMARY_TIMEOUT (optional, time difference needed between two last-primary-tiemstampe (lpt))
 #   OCF_RESKEY_SAPHanaFilter    (optional, should only be set if been told by support or for debugging purposes)
@@ -101,8 +101,8 @@ function saphana_usage() {
     local rc=0
     methods=$(saphana_methods)
     methods=$(echo $methods | tr ' ' '|')
-  cat <<-!
-	usage: $0 ($methods)
+    cat <<-EOF
+    usage: $0 ($methods)
 
     $0 manages a SAP HANA Instance as an HA resource.
 
@@ -116,8 +116,8 @@ function saphana_usage() {
     The 'validate-all' operation reports whether the parameters are valid
     The 'methods'      operation reports on the methods $0 supports
 
-	!
-	return $rc
+EOF
+    return $rc
 }
 
 #
@@ -128,11 +128,11 @@ function saphana_usage() {
 function saphana_meta_data() {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
     local rc=0
-	cat <<END
+    cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="SAPHana">
-<version>0.160.1.1</version>
+<version>0.160.1.3</version>
 
 <shortdesc lang="en">Manages two SAP HANA instances in system replication (SR).</shortdesc>
 <longdesc lang="en">
@@ -169,7 +169,7 @@ The resource agent uses the following four interfaces provided by SAP:
    Interface is SQL query into HANA (system replication table).  The hdbsql query will be replaced by a python script 
    "systemReplicationStatus.py" in SAP HANA SPS8 or 9.
    As long as we need to use hdbsql you need to setup secure store users for linux user root to be able to
-   access the SAP HANA database. You need to configure a secure store user key "SLEHALOC"/"RHELHALOC" which can connect the SAP
+   access the SAP HANA database. You need to configure a secure store user key "SLEHALOC" which can connect the SAP
    HANA database: 
 
 5. saphostctrl
@@ -267,7 +267,7 @@ function saphana_methods() {
     for m in start stop status monitor promote demote notify validate-all methods meta-data usage; do
         echo "$m"
     done
-	return $rc
+    return $rc
 }
 
 #
@@ -287,6 +287,7 @@ function dequote()
 function remoteHost2remoteNode()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
+    local -a clusterNodes=()
     local cl=""
     local vHost=""
     local remoteHost="$1"
@@ -390,7 +391,8 @@ function set_hana_attribute()
 #
 function assert() {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
-    local err_msg=$1 local default_rc=$OCF_NOT_RUNNING
+    local err_msg=$1 
+    local default_rc=$OCF_NOT_RUNNING
     # DONE: Check, if we need to destinguish between probe and others
     if ocf_is_probe; then
         default_exit=$OCF_NOT_RUNNING
@@ -442,7 +444,7 @@ scoring_crm_master()
     local roles="$1"
     local sync="$2"
     local skip=0
-    local myScore=-1
+    local myScore=-22 # TODO: PRIO3: Change back to -1 later
     for scan in "${SCORING_TABLE_PREFERRED_SITE_TAKEOVER[@]}"; do
         if [ $skip -eq 0 ]; then
             read rolePatt syncPatt score <<< $scan
@@ -485,7 +487,7 @@ function saphana_init() {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
     local rc=$OCF_SUCCESS
     local vName
-    local site
+    # local site
     # two parameter models (for transition only)
     # OLD: InstanceName
     # NEW: SID InstanceNumber
@@ -771,9 +773,9 @@ function check_for_primary() {
                   super_ocf_log info "FLOW $FUNCNAME rc=HANA_STATE_STANDALONE"
                   return $HANA_STATE_STANDALONE;;
            * )
-	          super_ocf_log err "ACT: check_for_primary:  we didn't expect node_status to be: <$node_status>"
+              super_ocf_log err "ACT: check_for_primary:  we didn't expect node_status to be: <$node_status>"
                   dump=$( echo $node_status | hexdump -C );
-	          super_ocf_log err "ACT: check_for_primary:  we didn't expect node_status to be: DUMP <$dump>"
+              super_ocf_log err "ACT: check_for_primary:  we didn't expect node_status to be: DUMP <$dump>"
                   node_full_status=$(su - ${sidadm} -c "hdbnsutil -sr_state" 2>/dev/null )
                   node_status=$(echo "$node_full_status" | awk '$1=="mode:" {print $2}')
                   super_ocf_log debug "DEC: check_for_primary: loop=$i: node_status=$node_status"
@@ -800,14 +802,15 @@ function analyze_hana_sync_statusSRS()
     super_ocf_log info "FLOW $FUNCNAME ($*)"
     local rc=-1 srRc=0 all_nodes_other_side="" local n="" master_lpt=""
     FULL_SR_STATUS=$(su - $sidadm -c "python $DIR_EXECUTABLE/python_support/systemReplicationStatus.py" 2>/dev/null); srRc=$?
+    super_ocf_log info "FLOW $FUNCNAME systemReplicationStatus.py -> $srRc"
     #
     # TODO: PRIO9: Here we might also need to filter additional sites (if multi tier should be supported)
     #              Could we define, that we always control site ID 1 and site ID 2?
-    all_nodes_other_site=$(echo "$FULL_SR_STATUS" | tr -d ' ' | awk -F'|' '$7==site { print $8}' site=$sr_name ); srRc=$?
-    all_nodes_local_site=$(echo "$FULL_SR_STATUS" | tr -d ' ' | awk -F'|' '$7==site { print $2}' site=$sr_name ); srRc=$?
+    all_nodes_other_site=$(echo "$FULL_SR_STATUS" | tr -d ' ' | awk -F'|' '$7==site { print $8}' site=$sr_name ); 
+    all_nodes_local_site=$(echo "$FULL_SR_STATUS" | tr -d ' ' | awk -F'|' '$7==site { print $2}' site=$sr_name );
     super_ocf_log info "DBG site=$sr_name, all_nodes_other_site=$all_nodes_other_site"
     #super_ocf_log info "DBG FULL_SR_STATUS=$FULL_SR_STATUS"
-    if [ $srRc -eq 5 ]; then
+    if [ $srRc -eq 15 ]; then
        super_ocf_log info "FLOW $FUNCNAME SOK"
        for n in $all_nodes_other_site; do
             super_ocf_log info "ACT site=$sr_name, seting SOK for node <$n>"
@@ -1094,7 +1097,7 @@ function saphana_validate() {
 function saphana_start_primary()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
-	local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
+    local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
     local lss sqlrc;
     local rc=0
     local lpa_dec=4
@@ -1226,7 +1229,6 @@ check_for_primary_master()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
     local rc=1
-    local otherHosts
     local ch ch_role
     #
     # get actual list of cluster members
@@ -1292,7 +1294,7 @@ wait_for_primary_master()
 function saphana_start_secondary()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
-	local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
+    local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
     local sqlrc;
     set_crm_master 0
     #
@@ -1335,6 +1337,69 @@ function saphana_start_secondary()
     fi
     super_ocf_log info "FLOW $FUNCNAME rc=$rc"
     return $rc
+}
+
+#
+# function: saphana_check_local_instance
+# params:
+# output:
+# rc:       rc=0 (UP) rc=1 (DOWN)
+# globals:
+#
+function saphana_check_local_instance()
+{
+    local rc=1
+    local count=0
+    local SERVNO
+    local output
+    local MONITOR_SERVICES="hdbnameserver|hdbdaemon" # TODO: PRIO1: exact list of Services
+    super_ocf_log info "FLOW $FUNCNAME ($*)"
+    check_sapstartsrv
+    rc=$?
+  if [ $rc -eq $OCF_SUCCESS ]
+  then
+    output=$($SAPCONTROL -nr $InstanceNr -function GetProcessList -format script)
+    # we have to parse the output, because the returncode doesn't tell anything about the instance status
+    for SERVNO in `echo "$output" | grep '^[0-9] ' | cut -d' ' -f1 | sort -u`
+    do
+      local COLOR=`echo "$output" | grep "^$SERVNO dispstatus: " | cut -d' ' -f3`
+      local SERVICE=`echo "$output" | grep "^$SERVNO name: " | cut -d' ' -f3`
+      local STATE=0
+      local SEARCH
+
+      case $COLOR in
+        GREEN|YELLOW)       STATE=$OCF_SUCCESS;;
+        *)                  STATE=$OCF_NOT_RUNNING;;
+      esac
+
+      SEARCH=`echo "$MONITOR_SERVICES" | sed 's/\+/\\\+/g' | sed 's/\./\\\./g'`
+      if [ `echo "$SERVICE" | egrep -c "$SEARCH"` -eq 1 ]
+      then
+          if [ $STATE -eq $OCF_NOT_RUNNING ]
+          then
+            [ "$MONLOG" != "NOLOG" ] && ocf_log err "SAP instance service $SERVICE is not running with status $COLOR !"
+            rc=$STATE
+          fi
+          count=1
+      fi
+    done
+
+    if [ $count -eq 0 -a $rc -eq $OCF_SUCCESS ]
+    then
+      if ocf_is_probe
+      then
+        rc=1
+      else
+        [ "$MONLOG" != "NOLOG" ] && ocf_log err "The SAP instance does not run any services which this RA could monitor!"
+        rc=1
+      fi
+    fi
+  fi
+
+
+    super_ocf_log info "FLOW $FUNCNAME rc=$rc"
+# FH BAUSTELLE
+    return $rc    
 }
 
 #
@@ -1508,6 +1573,8 @@ function lpa_check_lpt_status() {
     local LPTrem=-1
     local LPTMark=1000
     local delta=0
+    local remSn_name=""
+    local remHost=""
     #
     # First GET LPT from ATTR-FILE-DEFAULT
     #
@@ -1523,46 +1590,55 @@ function lpa_check_lpt_status() {
             LPTloc=20                           # DEFAULT
         fi
     fi
-            # TODO PRIO1: REMOVE remoteNode dependency - lpa_get_lpt
-    LPTrem=$(lpa_get_lpt $remoteNode); lparc=$?
-    if [ $lparc -ne 0 ]; then
-        # LPT of the other node could not be evaluated - LPA says WAIT
-        super_ocf_log debug "DBG: LPA: LPTloc=$LPTloc, LPTrem undefined ==> WAIT"
-        rc=2
-    else
-        super_ocf_log debug "DBG: LPA: LPTloc ($LPTloc) LPTrem ($LPTrem) delta ($delta)"
-        if [ $LPTloc -lt $LPTMark -a $LPTrem -lt $LPTMark ]; then
-           delta=0   # both lpts are not a real timestamp so just take the greater one
-        else
-           delta=$DUPLICATE_PRIMARY_TIMEOUT   # at least one of the lpts is a real timestamp so include delta-gap
-        fi
-        if (( delta < LPTloc - LPTrem )); then 
-            # We are the winner - LPA says STARTUP
-            super_ocf_log debug "DBG: LPA: LPTloc wins $LPTloc > $LPTrem + $delta ==> START"
-            rc=0
-        elif (( delta < LPTrem - LPTloc )); then 
-            if ocf_is_true "$AUTOMATED_REGISTER" ; then
-                # The other one has won - LPA says REGISTER
-                super_ocf_log debug "DBG: LPA: LPTrem wins $LPTrem > $LPTloc + $delta ==> REGISTER"
-                rc=1
-            else
-                super_ocf_log debug "DBG: LPA: LPTrem wins $LPTrem > $LPTloc + $delta BUT AUTOMATED_REGISTER='false' ==> WAIT"
-                rc=2
-            fi
+    for remHost in $otherNodes
+    do
+        remSn_name=$(get_hana_attribute ${remHost} ${ATTR_NAME_HANA_SITE[@]})              
+        if [ "$sr_name" != "$nSite" ]; then
+############### BAUSTELLE
 
-        else                                     
-            super_ocf_log debug "DBG: LPA: Difference between LPTloc and LPTrem is less than delta ($delta) ==> WAIT"
-            # TODO: PRIO3: ADD STALEMATE-HANDLING HERE; currently admin should set one of the lpa to 20
-            rc=2
-        fi        
-    fi    
+            LPTrem=$(lpa_get_lpt $remHost); lparc=$?
+            if [ $lparc -ne 0 ]; then
+                # LPT of the other node could not be evaluated - LPA says WAIT
+                super_ocf_log debug "DBG: LPA: LPTloc=$LPTloc, LPTrem undefined ==> WAIT"
+                rc=2
+            else
+                super_ocf_log debug "DBG: LPA: LPTloc ($LPTloc) LPTrem ($LPTrem) delta ($delta)"
+                if [ $LPTloc -lt $LPTMark -a $LPTrem -lt $LPTMark ]; then
+                   delta=0   # both lpts are not a real timestamp so just take the greater one
+                else
+                   delta=$DUPLICATE_PRIMARY_TIMEOUT   # at least one of the lpts is a real timestamp so include delta-gap
+                fi
+                if (( delta < LPTloc - LPTrem )); then 
+                    # We are the winner - LPA says STARTUP
+                    super_ocf_log debug "DBG: LPA: LPTloc wins $LPTloc > $LPTrem + $delta ==> START"
+                    if [ $rc -le 0 ]; then rc=0; fi
+                elif (( delta < LPTrem - LPTloc )); then 
+                    if ocf_is_true "$AUTOMATED_REGISTER" ; then
+                        # The other one has won - LPA says REGISTER
+                        super_ocf_log debug "DBG: LPA: LPTrem wins $LPTrem > $LPTloc + $delta ==> REGISTER"
+                        if [ $rc -le 1 ]; then rc=1; fi
+                    else
+                        super_ocf_log debug "DBG: LPA: LPTrem wins $LPTrem > $LPTloc + $delta BUT AUTOMATED_REGISTER='false' ==> WAIT"
+                        rc=2
+                    fi
+
+                else                                     
+                    super_ocf_log debug "DBG: LPA: Difference between LPTloc and LPTrem is less than delta ($delta) ==> WAIT"
+                    # TODO: PRIO3: ADD STALEMATE-HANDLING HERE; currently admin should set one of the lpa to 20
+                    rc=2
+                fi        
+            fi    
+        fi
+    done
     super_ocf_log info "FLOW $FUNCNAME rc=$rc"
     return $rc    
 }
 
 # function: is_master_nameserver
+# params:   -
 # rc:       0: yes its the master nameserver
 #           1: else
+# globals:  
 function is_master_nameserver()
 {
     local rc=1 nRole="" nLsc=""  nSrmode="" nNsConf="" nNsCurr="" nIsConf="" nIsCurr="" 
@@ -1593,7 +1669,7 @@ function is_master_nameserver()
 #
 function saphana_start_clone() {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
-	local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
+    local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
     local sqlrc;
     local chkusr;
     # TODO: PRIO4: remove check_secstore_users later
@@ -1619,9 +1695,6 @@ function saphana_start_clone() {
                 lpa_set_lpt  30
             fi
         fi
-        set_hana_attribute ${NODENAME} "DEMOTED" ${ATTR_NAME_HANA_CLONE_STATE[@]}    
-        super_ocf_log err  "ACT: Secure store users are missing (see best practice manual how to setup the users)"
-        rc=$OCF_SUCCESS;
     else
         set_hana_attribute ${NODENAME} "DEMOTED" ${ATTR_NAME_HANA_CLONE_STATE[@]}
         check_for_primary; primary_status=$?
@@ -1646,6 +1719,7 @@ function saphana_stop_clone() {
     local rc=0
     local primary_status="x"
     set_hana_attribute ${NODENAME} "UNDEFINED" ${ATTR_NAME_HANA_CLONE_STATE[@]}
+    super_ocf_log info "RA: SET UNDEFINED"
     #if is_master_nameserver; then
     check_for_primary; primary_status=$?
     if [ $primary_status -eq $HANA_STATE_SECONDARY ]; then
@@ -1874,8 +1948,8 @@ function saphana_monitor_primary()
 function saphana_monitor_secondary()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
-	local rc=$OCF_ERR_GENERIC
-	local promoted=0
+    local rc=$OCF_ERR_GENERIC
+    local promoted=0
     local init_attribute=0
     local lss
     #
@@ -1981,11 +2055,11 @@ function saphana_monitor_clone() {
     #       a) returning 7 here and force cluster a restart of the slave
     #       b) starting the instance here inside the monitor -> may result in longer runtime, timeouts
     #
-	# first check with the status function (OS tools) if there could be something like a SAP instance running
-	# as we do not know here, if we are in master or slave state we do not want to start our monitoring
-	# agents (sapstartsrv) on the wrong host
-	local rc=$OCF_ERR_GENERIC
-	local promoted=0
+    # first check with the status function (OS tools) if there could be something like a SAP instance running
+    # as we do not know here, if we are in master or slave state we do not want to start our monitoring
+    # agents (sapstartsrv) on the wrong host
+    local rc=$OCF_ERR_GENERIC
+    local promoted=0
     local init_attribute=0
     local nState=""
 
@@ -1993,11 +2067,11 @@ function saphana_monitor_clone() {
     my_sync=$(get_hana_attribute ${NODENAME} ${ATTR_NAME_HANA_SYNC_STATUS[@]})
     lpa_check_lpt_status  # TODO: PRIO3 : remove that line later - its only to call lpa_check_lpt_status much more often for checking
 
-	if ocf_is_probe; then
-		super_ocf_log debug "DBG: PROBE ONLY"
-	else
-		super_ocf_log debug "DBG: REGULAR MONITOR"
-	fi
+    if ocf_is_probe; then
+        super_ocf_log debug "DBG: PROBE ONLY"
+    else
+        super_ocf_log debug "DBG: REGULAR MONITOR"
+    fi
     if is_master_nameserver; then
         #
         # First check, if we are PRIMARY or SECONDARY
@@ -2005,17 +2079,15 @@ function saphana_monitor_clone() {
         check_for_primary; primary_status=$?
         if [ $primary_status -eq $HANA_STATE_PRIMARY ]; then
             saphana_monitor_primary; rc=$?
-        else
-            if [ $primary_status -eq $HANA_STATE_SECONDARY  ]; then
+        elif [ $primary_status -eq $HANA_STATE_SECONDARY  ]; then
                 saphana_monitor_secondary; rc=$?
-            else
+        else
                 #
                 # OK, we are neither HANA PRIMARY nor HANA SECONDARY
                 #
                 super_ocf_log warn "ACT: saphana_monitor_clone: HANA_STATE_DEFECT"
                 # TODO: PRIO2: Or only set_crm_master -INFINITY ?
                 rc=$OCF_ERR_GENERIC
-            fi
         fi
     else
         nState=$(get_hana_attribute ${NODENAME} ${ATTR_NAME_HANA_CLONE_STATE[@]})
@@ -2023,12 +2095,29 @@ function saphana_monitor_clone() {
         my_sync=$(get_hana_attribute ${NODENAME} ${ATTR_NAME_HANA_SYNC_STATUS[@]})
         scoring_crm_master "$my_role" "$my_sync"
         # TODO: PRIO1: Check when we can start to monitor the local instance!! ==> instance restart
-        case "$nState" in
-            DEMOTED ) rc=$OCF_SUCCESS;;
-            PROMOTED ) rc=$OCF_RUNNING_MASTER;;
-            UNDEFINED ) rc=$OCF_NOT_RUNNING;;
-            * ) rc=$OCF_NOT_RUNNING;;
-        esac
+##### FH BAUSTELLE
+        if saphana_check_local_instance; then
+            case "$nState" in
+                DEMOTED ) rc=$OCF_SUCCESS;;
+                PROMOTED ) rc=$OCF_RUNNING_MASTER;;
+                UNDEFINED ) rc=$OCF_NOT_RUNNING;;
+                * ) rc=$OCF_NOT_RUNNING;;
+            esac
+           if [ $primary_status -eq $HANA_STATE_PRIMARY ]; then
+                local placeholder=1
+           elif [ $primary_status -eq $HANA_STATE_SECONDARY  ]; then
+                lpa_set_lpt  30
+           else
+                super_ocf_log warn "ACT: saphana_monitor_clone: HANA_STATE_DEFECT"
+           fi
+        else
+	    case "$nState" in
+                 DEMOTED ) rc=$OCF_NOT_RUNNING;;
+                 PROMOTED ) rc=$OCF_NOT_RUNNING;; ## TODO: PRIO 3: FAILED_MASTER?
+                 UNDEFINED ) rc=$OCF_NOT_RUNNING;;
+                 * ) rc=$OCF_NOT_RUNNING;;
+            esac
+        fi
     fi
     super_ocf_log info "FLOW $FUNCNAME rc=$rc"
     return $rc
