SAPHana: All actions for the complete swarm (start/stop/takeover/register) will only be done at the master nameserver

diff --git a/SAPHana/SAPHana b/SAPHana/SAPHana
--- a/SAPHana/SAPHana
+++ b/SAPHana/SAPHana
@@ -1034,26 +1034,31 @@ function saphana_start() {
     #
     # DONE: ASK: PRIO5: For SCALE-OUT - do we need to use an other call like StartSystem? Or better to use the HDB command?
     #
-    if [ $rc -eq $OCF_SUCCESS ]; then
-        output=$($SAPCONTROL -nr $InstanceNr -function StartSystem)
-        rc=$?
-        super_ocf_log info "ACT: Starting SAPHANA Instance $SID-$InstanceName: $output"
-    fi
-    if [ $rc -eq 0 ]
-    then
-        # TODO: PRIO9: something more dynamic than 3600 seconds in WaitforStarted
-        output=$($SAPCONTROL -nr $InstanceNr -function WaitforStarted 3600 1)
-        if [ $? -eq 0 ]
+    if is_the_master_nameserver; then
+        if [ $rc -eq $OCF_SUCCESS ]; then
+            output=$($SAPCONTROL -nr $InstanceNr -function StartSystem)
+            rc=$?
+            super_ocf_log info "ACT: Starting SAPHANA Instance $SID-$InstanceName: $output"
+        fi
+        if [ $rc -eq 0 ]
         then
-            super_ocf_log info "ACT: SAPHANA Instance $SID-$InstanceName started: $output"
-            rc=$OCF_SUCCESS
+            # TODO: PRIO9: something more dynamic than 3600 seconds in WaitforStarted
+            output=$($SAPCONTROL -nr $InstanceNr -function WaitforStarted 3600 1)
+            if [ $? -eq 0 ]
+            then
+                super_ocf_log info "ACT: SAPHANA Instance $SID-$InstanceName started: $output"
+                rc=$OCF_SUCCESS
+            else
+                super_ocf_log err "ACT: SAPHANA Instance $SID-$InstanceName start failed: $output"
+                rc=$OCF_ERR_GENERIC
+            fi
         else
             super_ocf_log err "ACT: SAPHANA Instance $SID-$InstanceName start failed: $output"
             rc=$OCF_ERR_GENERIC
         fi
     else
-        super_ocf_log err "ACT: SAPHANA Instance $SID-$InstanceName start failed: $output"
-        rc=$OCF_ERR_GENERIC
+        # TODO: PRIO1: Do we need to set a clone state here?
+        rc=$OCF_SUCCESS
     fi
     super_ocf_log info "FLOW $FUNCNAME rc=$rc"
     return $rc
@@ -1066,33 +1071,39 @@ function saphana_start() {
 # saphana_stop: Stop the SAP instance
 #
 function saphana_stop() {
-  super_ocf_log info "FLOW $FUNCNAME ($*)"
-  local output=""
-  local rc=0
-  check_sapstartsrv; rc=$?
-  if [ $rc -eq $OCF_SUCCESS ]; then
-    ## TODO: PRIO 1: Only stop System, if I am the last master!
-    output=$($SAPCONTROL -nr $InstanceNr -function Stop)
-    rc=$?
-    super_ocf_log info "ACT: Stopping SAP Instance $SID-$InstanceName: $output"
-  fi
-  if [ $rc -eq 0 ]
-  then
-    output=$($SAPCONTROL -nr $InstanceNr -function WaitforStopped 3600 1)
-    if [ $? -eq 0 ]
-    then
-      super_ocf_log info "ACT: SAP Instance $SID-$InstanceName stopped: $output"
-      rc=$OCF_SUCCESS
+    super_ocf_log info "FLOW $FUNCNAME ($*)"
+    local output=""
+    local rc=0
+    check_sapstartsrv; rc=$?
+    if is_the_master_nameserver; then
+       if [ $rc -eq $OCF_SUCCESS ]; then
+          ## TODO: PRIO 1: Only stop System, if I am the last master!
+          ## TODO: PRIO 2: Do we need a "last-man-switch-of-the-light" detection?
+          output=$($SAPCONTROL -nr $InstanceNr -function StopSystem)
+          rc=$?
+          super_ocf_log info "ACT: Stopping SAP Instance $SID-$InstanceName: $output"
+       fi
+       if [ $rc -eq 0 ]
+       then
+           output=$($SAPCONTROL -nr $InstanceNr -function WaitforStopped 3600 1)
+           if [ $? -eq 0 ]
+           then
+               super_ocf_log info "ACT: SAP Instance $SID-$InstanceName stopped: $output"
+               rc=$OCF_SUCCESS
+           else
+               super_ocf_log err "ACT: SAP Instance $SID-$InstanceName stop failed: $output"
+               rc=$OCF_ERR_GENERIC
+           fi
+       else
+           super_ocf_log err "ACT: SAP Instance $SID-$InstanceName stop failed: $output"
+           rc=$OCF_ERR_GENERIC
+       fi
     else
-      super_ocf_log err "ACT: SAP Instance $SID-$InstanceName stop failed: $output"
-      rc=$OCF_ERR_GENERIC
+        # TODO: PRIO1: Do we need to set a clone state here?
+        rc=$OCF_SUCCESS
     fi
-  else
-    super_ocf_log err "ACT: SAP Instance $SID-$InstanceName stop failed: $output"
-    rc=$OCF_ERR_GENERIC
-  fi
-  super_ocf_log info "FLOW $FUNCNAME rc=$rc"
-  return $rc
+    super_ocf_log info "FLOW $FUNCNAME rc=$rc"
+    return $rc
 }
 
 #
@@ -1183,7 +1194,7 @@ function saphana_start_primary()
                     rc=$OCF_SUCCSESS
                     ;;
                 1 ) # landcape says we are down, lets start and adjust scores and return code
-                    super_ocf_log info "LPA: landcape: DOWN, LPA: start ==> start instance"
+                    super_ocf_log info "LPA: landcape: DOWN, LPA: start ==> start system"
                     saphana_start
                     rc=$?                    
                     LPTloc=$(date '+%s')
@@ -2318,19 +2329,21 @@ function saphana_promote_clone() {
         hana_sync=$(get_hana_attribute ${NODENAME} ${ATTR_NAME_HANA_SYNC_STATUS[@]})
         case "$hana_sync" in
              SOK )
-                super_ocf_log info "ACT: !!!!!!! Promote REPLICA $SID-$InstanceName to be primary. !!!!!!"
-                LPTloc=$(date '+%s')
-                # lpa_set_lpt 20 $remoteNode
-                lpa_set_lpt $LPTloc
-                lpa_push_lpt $LPTloc
-                backup_global_and_nameserver
-                su - $sidadm -c "hdbnsutil -sr_takeover"
-                backup_global_and_nameserver
-                #
-                # now gain check, if we are primary NOW
-                #
-                # TODO: PRIO3: check, if we need to destinguish between HANA_STATE_PRIMARY, HANA_STATE_SECONDARY, HANA_STATE_DEFECT
-                #
+                if is_the_master_nameserver; then
+                    super_ocf_log info "ACT: !!!!!!! Promote REPLICA $SID-$InstanceName to be primary. !!!!!!"
+                    LPTloc=$(date '+%s')
+                    # lpa_set_lpt 20 $remoteNode
+                    lpa_set_lpt $LPTloc
+                    lpa_push_lpt $LPTloc
+                    backup_global_and_nameserver
+                    su - $sidadm -c "hdbnsutil -sr_takeover"
+                    backup_global_and_nameserver
+                    #
+                    # now gain check, if we are primary NOW
+                    #
+                    # TODO: PRIO3: check, if we need to destinguish between HANA_STATE_PRIMARY, HANA_STATE_SECONDARY, HANA_STATE_DEFECT
+                    #
+                fi
                 if check_for_primary; then
                     rc=$OCF_SUCCESS;
                 else
